"""Pre-flight check. Run before pushing:  python tools/check.py

Verifies every image the README points at actually exists, that cache-busting
strings are consistent, that the SVGs parse, and that no placeholder text is
about to go public.
"""

import os, re, sys, glob
import xml.dom.minidom as minidom

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
README = os.path.join(ROOT, "README.md")

ok, warn, fail = [], [], []


def check_svgs():
    files = sorted(glob.glob(os.path.join(ROOT, "assets", "*.svg")))
    bad = []
    for f in files:
        try:
            minidom.parse(f)
        except Exception as e:
            bad.append(f"{os.path.basename(f)}: {str(e)[:60]}")
    if bad:
        fail.append("SVGs that do not parse:\n    " + "\n    ".join(bad))
    else:
        ok.append(f"{len(files)} SVGs parse cleanly")


def check_refs(text):
    refs = set(re.findall(r'(?:src|srcset)="\./([^"?]+)', text))
    missing, pending = [], []
    for r in sorted(refs):
        if not os.path.exists(os.path.join(ROOT, r)):
            (pending if r.startswith("output/") else missing).append(r)
    if missing:
        fail.append("README points at files that do not exist:\n    " + "\n    ".join(missing))
    else:
        ok.append(f"all {len(refs) - len(pending)} local images referenced by the README exist")
    if pending:
        warn.append("generated by a workflow, so broken until it runs once:\n    " + "\n    ".join(pending)
                    + "\n    -> run the 'contribution snake' workflow from the Actions tab after pushing")


def check_version(text):
    vs = set(re.findall(r"\?v=([0-9A-Za-z._-]+)", text))
    if len(vs) > 1:
        warn.append(f"mixed cache-busting strings: {', '.join(sorted(vs))} - use one value everywhere")
    elif vs:
        ok.append(f"cache busting consistent (?v={vs.pop()})")


def check_placeholders(text):
    if "your-email@example.com" in text:
        fail.append("README still contains the placeholder your-email@example.com")
    else:
        ok.append("no placeholder email in the README")


def check_data():
    c = os.path.join(ROOT, "data", "contributions.json")
    s = os.path.join(ROOT, "data", "stats.json")
    if os.path.exists(c) and os.path.exists(s):
        ok.append("GitHub data synced - matrix and cards show real numbers")
    else:
        warn.append("data/ not synced yet: the matrix says AWAITING FIRST SYNC and the\n"
                    "    cards show a dash. The hud workflow fixes this on your first push.")


def check_size():
    total = sum(os.path.getsize(f) for f in glob.glob(os.path.join(ROOT, "assets", "*")))
    mb = total / 1024 / 1024
    (ok if mb < 3 else warn).append(f"assets total {mb:.1f} MB")


def main():
    if not os.path.exists(README):
        print("no README.md found next to tools/")
        return 1
    text = open(README).read()
    check_svgs(); check_refs(text); check_version(text)
    check_placeholders(text); check_data(); check_size()

    for m in ok:
        print(f"  ok    {m}")
    for m in warn:
        print(f"  note  {m}")
    for m in fail:
        print(f"  FIX   {m}")
    print()
    if fail:
        print(f"{len(fail)} thing(s) to fix before pushing.")
        return 1
    print("ready to push.")
    return 0


if __name__ == "__main__":
    sys.exit(main())